### ISSUE TITLE
Limit content length when producing URL

### ISSUE THREAD

**Issue by regisphilibert** [theNewDynamic/hugo-module-calendar#1]
Currently we pass the `.Content` of the event content file as is. When the content is big or heavy in HTML this obviously triggers some bad URL. 

We should:
- [x] Use . Plain instead of content (@mountainbug95 let me know if HTML is handled well, but I doubt it. Update: it is not:))
- [x] Estimate the size of the .Plain before using it (I guess by counting `.PlainWords`), and if we judge too big, truncate it.

**Comment by mountainbug95** [comment]
@regisphilibert This was resolved in commit 26e15388691f6343a35137f68c4d2be58a3e0952
