### ISSUE TITLE
Update front logic to get rid of tailwind dependance

### ISSUE THREAD

**Issue by maknetaRo** [theNewDynamic/hugo-module-calendar#6]
The function doesn't work or doesn't have an effect because there aren't any CSS files attached to it to use the class "hidden" or "active"

**Comment by regisphilibert** [comment]
Hello @maknetaRo if you have time I'd love for you test this [PR](https://github.com/theNewDynamic/hugo-module-tnd-addtocal/pull/8) I just created. It basically strips any former dependency to Tailwindcss classes for the front logic. It means you don't need any custom css or js for it to work out of the box.

It's not using the `.hidden` or `.active` class anymore but the `aria-expanded` attribute so js and style don't overlap.

To test drive it as a hugo module you can just use the Hugo CLI with the following command:

```
hugo mod get -u github.com/theNewDynamic/hugo-module-tnd-addtocal@c40f520fb18458883f1cd8e7d4a51136a3d84e04
```

Thanks a ton!

**Comment by maknetaRo** [comment]
Yes, it works now with that command (although in meantime I did my own changes in css).
